/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class PubkeyIndexMap {
  constructor()
  static withInitialCapacity(capacity: number): PubkeyIndexMap
  set(key: Uint8Array, value: number): void
  get(key: Uint8Array): number | null
  has(key: Uint8Array): boolean
  delete(key: Uint8Array): number | null
  get size(): number
  clear(): void
  clone(): PubkeyIndexMap
}
