/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class PubkeyIndexMap {
  constructor()
  set(key: Uint8Array, value: Val): Val | null
  get(key: Uint8Array): Val | null
  has(key: Uint8Array): boolean
  delete(key: Uint8Array): Val | null
  get size(): Val
  clear(): void
  clone(): PubkeyIndexMap
}
